### ISSUE TITLE
metamask + iron = website confused

### ISSUE THREAD

**Issue by naps62** [wevm/mipd#6]
After applying https://github.com/iron-wallet/iron/pull/352, I installed the Iron extension on my main browser profile (predicting something would go wrong, but testing for that was the point)

with both extensions installed, the first website I used happened to be https://app.charmverse.io/
took me a while to connect the dots with this, but the "Connect Wallet" (metamask) button is now redirecting to the chrome app store. disabling the Iron extension makes it connect to Metamask normally

Is there a way around this?
I'm assuming the long-term answer is that both a) metamask needs to support 6963, and b) whatever sdk is used by charmverse needs to be updated as well, but wondering if some viable solution is possible for legacy pages?

the EIP does mention that backwards compatiblity is supposed to happen (by still supporting `window.ethereum`) so maybe this is a bug / wrong assumption on whatever SDK the website uses?

**Comment by naps62** [comment]
Come to think of it, maybe this is the double `window.ethereum` injection?

**Comment by glitch-txs** [comment]
You should add backward compatibility for window.ethereum for websites that don't support 6963 :)

https://eips.ethereum.org/EIPS/eip-6963
